name: CI Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:

# MAUI Windows Build
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install canker Workload
        run: dotnet workload install canker --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore canker/canker.csproj

      - name: Build canker Windows
        run: dotnet publish canker/canker.csproj -c Release -f net7.0-windows10.0.19041.0 --no-restore /p:PublishReadyToRun=false

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: canker-windows-ci-build
          path: canker/bin/Release/net7.0-windows10.0.19041.0/win10-x64/AppPackages/canker*/canker*.msix
